### ISSUE TITLE
Cant mount essential.exefs

### ISSUE THREAD

**Issue by Lucstor** [ihaveamac/ninfs#111]
I think my essential.exefs file might be corrupted, when I run it and put a mount point and press next, it spits out this error
Is this the program or my fault?

Command: ['C:\\Users\\xxxxx\\AppData\\Local\\ninfs\\ninfs.exe',
 'exefs',
 'D:/Downloads/essential.exefs',
 '-f',
 'B:']

Traceback (most recent call last):
  File "C:\Users\Gordon Freeman\AppData\Roaming\Python\Python38\site-packages\pyctr\type\exefs.py", line 235, in __init__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfa in position 1: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Gordon Freeman\AppData\Roaming\Python\Python38\site-packages\cx_Freeze\initscripts\__startup__.py", line 124, in run
  File "C:\Users\Gordon Freeman\AppData\Roaming\Python\Python38\site-packages\cx_Freeze\initscripts\console.py", line 16, in run
  File "ninfs\_frozen_main.py", line 29, in <module>
  File "C:\Users\Gordon Freeman\Desktop\ninfs\ninfs\main.py", line 161, in gui
  File "C:\Users\Gordon Freeman\Desktop\ninfs\ninfs\main.py", line 106, in mount
  File "C:\Users\Gordon Freeman\Desktop\ninfs\ninfs\mount\exefs.py", line 158, in main
  File "C:\Users\Gordon Freeman\AppData\Roaming\Python\Python38\site-packages\pyctr\type\exefs.py", line 237, in __init__
pyctr.type.exefs.ExeFSNameError: could not decode from ascii: b'\x10\xfaw\xaa\xa4&\x01\xda'
Failed to do AttachConsole(27656): 0
(Note: this most likely isn't the cause of any other issues you might have!)

Return code was 1

**Comment by ihaveamac** [comment]
It's probably corrupted. Try viewing it in a hex editor, if you can't see names at the start of the file, it is not a valid ExeFS.

**Comment by Lucstor** [comment]
I looked and it it just some weird characters, It is probably corrupted. Is there any way I can get it back?

**Comment by ihaveamac** [comment]
Find a non-corrupted version of it. Sorry.
